# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fb195d7ad8b683af84ea6558eb9867def2af405492d9642d662c1266039188cd41495bdf38dd6766bb43cfec19dacff4a1adf641137ebd4f1b2797c5fa6d011

test:
  secret_key_base: 6a30f4fe0e6fdb11fc0491a532b70d7e022dd2ca0d80061ce6c8f6712d5082361e2f5093690cfc6222acde3686114448d9604d5be0eb11524980f0d146b0ba70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
